"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 18:53:08.137176
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


APPEND_ONLY_TABLES = (
    "case_data_versions",
    "human_review_events",
    "audit_events",
    "review_item_events",
)


def _append_only_triggers() -> None:
    """Make audit tables append-only at the database level (SQLite)."""
    if op.get_bind().dialect.name != "sqlite":
        return
    for table in APPEND_ONLY_TABLES:
        for verb in ("UPDATE", "DELETE"):
            op.execute(
                f"CREATE TRIGGER IF NOT EXISTS {table}_no_{verb.lower()} BEFORE {verb} ON {table} "
                f"BEGIN SELECT RAISE(ABORT, '{table} is append-only'); END;"
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_ts"), ["ts"], unique=False)

    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_name", sa.String(length=300), nullable=False),
        sa.Column("listing_route", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cases_status"), ["status"], unique=False)

    op.create_table(
        "case_data_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("extraction_run_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "version"),
    )
    with op.batch_alter_table("case_data_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_case_data_versions_case_id"), ["case_id"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_name", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("doc_type", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=60), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("quality", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=20), nullable=True),
        sa.Column("uploaded_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "sha256"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_status"), ["status"], unique=False)

    op.create_table(
        "reports",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("data_version", sa.Integer(), nullable=True),
        sa.Column("ruleset_version", sa.String(length=20), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=True),
        sa.Column("legacy_status", sa.String(length=20), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=True),
        sa.Column("company_name", sa.String(length=300), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("report_id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_outcome"), ["outcome"], unique=False)

    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_version", sa.String(length=20), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("environment", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("pages", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extraction_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extraction_runs_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "human_reviews",
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("machine_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["reports.report_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("report_id"),
    )
    op.create_table(
        "field_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("field_path", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("selected", sa.JSON(), nullable=True),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("field_results", schema=None) as batch_op:
        batch_op.create_index("ix_field_results_run_field", ["run_id", "field_path"], unique=False)

    op.create_table(
        "human_review_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reviewer_name", sa.String(length=200), nullable=True),
        sa.Column("decision", sa.String(length=40), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["human_reviews.review_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("human_review_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_human_review_events_review_id"), ["review_id"], unique=False
        )

    op.create_table(
        "review_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("field_path", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("field_status", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("proposed", sa.JSON(), nullable=True),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_items_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_items_status"), ["status"], unique=False)

    op.create_table(
        "review_item_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("original_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("data_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["review_items.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_item_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_item_events_item_id"), ["item_id"], unique=False
        )

    # ### end Alembic commands ###
    _append_only_triggers()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_item_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_item_events_item_id"))

    op.drop_table("review_item_events")
    with op.batch_alter_table("review_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_items_status"))
        batch_op.drop_index(batch_op.f("ix_review_items_case_id"))

    op.drop_table("review_items")
    with op.batch_alter_table("human_review_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_human_review_events_review_id"))

    op.drop_table("human_review_events")
    with op.batch_alter_table("field_results", schema=None) as batch_op:
        batch_op.drop_index("ix_field_results_run_field")

    op.drop_table("field_results")
    op.drop_table("human_reviews")
    with op.batch_alter_table("extraction_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extraction_runs_document_id"))

    op.drop_table("extraction_runs")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_outcome"))
        batch_op.drop_index(batch_op.f("ix_reports_case_id"))

    op.drop_table("reports")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_status"))
        batch_op.drop_index(batch_op.f("ix_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_documents_case_id"))

    op.drop_table("documents")
    with op.batch_alter_table("case_data_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_case_data_versions_case_id"))

    op.drop_table("case_data_versions")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_status"))

    op.drop_table("cases")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_ts"))
        batch_op.drop_index(batch_op.f("ix_audit_events_case_id"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
